# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CheerpJ - Documentation
description: >- # this means to ignore newlines until "baseurl:"
  Main documentation for CheerpJ Applet Runner | Run Java content in your Browser
baseurl: "/cheerpj-appletrunner" # the subpath of your site, e.g. /blog
logo: "/assets/cheerpj_logo.png"   # Change to relevant file
tagline:
  line1: "CheerpJ Applet Runner"
  line2: "Documentation & FAQs"

social_links:
  twitter: leaningtech
  github:  leaningtech
  medium:  leaningtech
  linkedin: leaning-technologies-Ltd

chrome: "https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein"
edge: "https://microsoftedge.microsoft.com/addons/detail/cheerpj-applet-runner/ebfcpaoldmijengghefpohddmfpndmic"
privacy: "https://leaningtech.com/privacy-policy-cheerpj-ar/"

# Build settings
markdown: kramdown
remote_theme: leaningtech/leaningtech-docs

plugins:
 - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: "https://opengraph.githubassets.com/0695f40a0d2d9ee5d8871e5f80042de3b061f7496b092d086712709c9d0f1a6e/leaningtech/cheerpj-appletrunner"

repository: https://github.com/leaningtech/cheerpj-appletrunner
website: https://leaningtech.com/cheerpj-applet-runner/
issues: https://github.com/leaningtech/cheerpj-appletrunner/issues
chat: https://gitter.im/leaningtech/cheerp
blog: https://medium.com/leaningtech
has_about: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
